### PR TITLE
Support to Perl files and Exclusion of instructions from analyze

### PR DESCRIPTION
**Pull request by darold**
This PR include several improvements:

- Fix detection of the Oracle ASCII function.
- Add -E, --exclude-instr command line option to be able to exclude
- Add support to Perl file analyze using extensions pl and pm.
- Add documentation about -E or --exclude-instr option

### CODE REVIEW

**Comment by darold** [comment]
Hi Anthony

Actually I had lot of false positive with some instruction like USER or DELETE_WITHOUT_FROM in some Java JSP file so I find useful to be able to exclude them from the report.

I have also processed hundred of Perl files containing SQL queries so I have added the support in code2pg. For the moment it only support string with double quote but I will add support to `qq{}` notation when I will have more time.

Thanks for this useful tool, this is a good companion to Ora2Pg :-)

**Comment by e7e6** [comment]
Hi Gilles,
thanks for the pull request. I will have a detailled look at it (just coming back from vacation).
Anthony

**Review by e7e6 — COMMENTED** [review]
Good point about man-days and person-days, thanks for raising it.

**Review by e7e6 — COMMENTED** [review]
Regarding perl file support, it seems the` %LANGUAGE_COMMENTS_*` are only used to edit the file and add comments for user review and not to remove those lines from the search. This would be more interesting for sure and don't remember if it was not integrated due to laziness or big performance issues (makes a while).

Therefore the "Add support to Perl file analyze using extensions pl and pm" commit will not break anything... But will not be reached in the part of the code we might expect it to be reached.

**Comment by darold** [comment]
Hum right, looks that this is not the right patch, actually the hash key should be 'pl' and 'pm' instead of just 'perl' let me look at this.

**Comment by darold** [comment]
My last comment is wrong, I don't remember exactly what was done. Don't waste time on this I will check what I have exactly done to add Perl support.

**Comment by darold** [comment]
Ok I have found what I have done before switching to more complex code to support `qq{...}` Perl notation. I have pushed the missing code in previous patch to add minimal support for Perl language.

I have also add a fix to eliminate other false positive with the DELETE_WITHOUT_FROM. Honestly this rule brings too much false positive and imo it should be removed when it is not plain SQL statements.

**Comment by e7e6** [comment]
Hi Gilles,
best new year wishes first of all. What you have proposed should have been accepted long ago... so are you ok to re-open the PR and have it integrated here ?
Anthony

**Comment by darold** [comment]
I have answered privately to your gmail address, let me know if it doesn't work anymore.

**Pull request closed without merging**
